environment:
  nodejs_version: "5.1.0"

install:
  - choco install gitversion.portable -pre -y
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulp

test_script:
  - ps: gitversion /l console /output buildserver

  - ps: .\Deployment\Update-TaskVersion.ps1 .\Tasks\AuthenticateGitRemoteAccess\task.json $env:GitVersion_Major $env:GitVersion_Minor $env:GitVersion_Patch
  - ps: .\Deployment\Update-ExtensionVersion.ps1 .\vss-extension.json $env:GitVersion_MajorMinorPatch

  - gulp package
  
  - cmd: 7z a "AuthenticateGitRemoteAccess_%GitVersion_NuGetVersion%.zip" -r .\_build\Tasks\AuthenticateGitRemoteAccess\*.*
  - cmd: appveyor PushArtifact "AuthenticateGitRemoteAccess_%GitVersion_NuGetVersion%.zip"
  
  - cmd: appveyor PushArtifact ".\_build\Extensions\ioz.vsts-git-tasks-%GitVersion_MajorMinorPatch%.vsix"
  
build: off